services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
parameters:
    app.authorization: 'yyv0kg2yopv5x91lrwmyfttw0pmdk8',
    app.client-id: 'jhch4uoxcoh2d4wc77joe05ff6q8vz'